# Generated by Django 3.2.20 on 2023-08-24 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0002_alter_booking_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.CharField(choices=[('3 PM', '3 PM'), ('3:30 PM', '3:30 PM'), ('4 PM', '4 PM'), ('4:30 PM', '4:30 PM'), ('5 PM', '5 PM'), ('5:30 PM', '5:30 PM'), ('6 PM', '6 PM'), ('6:30 PM', '6:30 PM'), ('7 PM', '7 PM'), ('7:30 PM', '7:30 PM'), ('8 PM', '8 PM'), ('8:30 PM', '8:30 PM'), ('9 PM', '9 PM'), ('9:30 PM', '9:30 PM')], default='3 PM', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
