# Generated by Django 3.2.20 on 2023-08-24 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_review_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='email',
        ),
    ]
