# Generated by Django 3.2.20 on 2023-08-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_review_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.AlterField(
            model_name='booking',
            name='guests',
            field=models.IntegerField(default='1'),
        ),
    ]
